---
title: "IPS"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### Read and clean data set
```{r, fig.show='hold'}
library(corrplot)
data(ips_clean)
# fix(input)
# rename NC for missing data as NA
ips <- ips_clean
# ips <- as.data.frame(apply(ips, 2, function(x) gsub("-/-",NA,x)))
# 
# ips$daYN <- "yes" # a
# ips$daYN[ips$da == "d"] <- "no" # d
# ips$daYN <- as.factor(ips$daYN)

str(ips)
```


### Convert data set to class gpm
```{r, fig.show='hold'}
meta <- createGPMMeta(dataset = ips, 
                      selector = 1, response = c(2), 
                      independent = c(5:3038), meta = NULL)
ips <- gpm(ips, meta)
```


### Compile model evaluation dataset
```{r, fig.show='hold'}
summary(ips@data$input$daYN)

ips_resamples <- resamplingsByVariable(x = ips@data$input, 
                                       selector = as.character(unlist(ips@data$input[ips@meta$input$RESPONSE])), grabs = 20, 
                                       resample = 1000)

ips_trte <- splitMultResp(x = ips@data$input, 
                          p = 0.75,
                          response = ips@meta$input$RESPONSE,
                          resamples = ips_resamples)
```


```{r, fig.show='hold'}
response <- ips@meta$input$RESPONSE
independent <- ips@meta$input$INDEPENDENT
data(var_imp)
var_imp_top <- var_imp[[1]][var_imp[[1]]$n >= 50, ]
nrow(var_imp_top)
independent_top <-var_imp_top$VARIABLE 

# models <- trainModel(x = ips, 
#                      response = response, 
#                      independent = independent,
#                      resamples = ips_trte, 
#                      n_var = seq(5,200,20))

models <- trainModel(x = ips, 
                     response = response, 
                     independent = independent_top,
                     resamples = ips_trte,  
                     mode = "ffs",
                     n_var = seq(5,200,20), 
                     mthd = "rf", seed_nbr = 11, cv_nbr = 2)
save(model, file = "model_lars.Rdata")
var_imp <- compVarImp(models)

var_imp_plot <- plotVarImp(var_imp)

var_imp_heat <- plotVarImpHeatmap(var_imp, xlab = "Species", ylab = "Band")

tests <- compContTests(models)
```


